spring.application.name=api-gateway

server.port=9090
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Enable discovery routing
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/user-service/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/user-service/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[1].id=operator-service
spring.cloud.gateway.routes[1].uri=lb://OPERATOR-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/operator-service/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/operator-service/(?<segment>.*), /${segment}




# Actuator
management.endpoints.web.exposure.include=*