spring.application.name=config-server
server.port=8888
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}

# LOCAL CONFIG STORAGE (Simple for now)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config

spring.cloud.config.server.overrides.spring.cloud.config.override-none=true
spring.cloud.config.server.encrypt.enabled=false
